### ISSUE TITLE
Where is vim-airline color scheme?

### ISSUE THREAD

**Issue by Robert-M-Muench** [jordwalke/VimBox#27]
Docs state: "VimBox includes vim-airline and Spacegray color scheme."

But there is no such color scheme. If I use vim-airline, the default color scheme is used.

**Comment by jordwalke** [comment]
Can you screenshot please?

The plugins (including vim color schemes) are all downloaded into `~/.vim/bundle/`.

The `spacegray` color scheme is defined in the `VimCleanColors` bundle in that directory, including the corresponding airline theme.

The color scheme `spacegray` is activated [here](https://github.com/jordwalke/VimBox/blob/master/dotVim/guiSettingsVimRc).

**Comment by jordwalke** [comment]
Are you using `MacVim`? (VimBox is tested on MacVim).

**Comment by Robert-M-Muench** [comment]
Yes, I use MacVim.

This is what I see in the `VimCleanColors` directory:
`lightBright.vim
lightBrightMuted.vim
solarizedLight.vim
spacegray.vim`

and in the autoload directory:
`lightBright.vim
solarizedLight.vim`

Could it be that a reference to `vim-airline` is wrong? How is the theme named?

**Comment by jordwalke** [comment]
Oh, I misunderstood. So, `spacegray` and many other colorschemes will use the special airline colorscheme that dynamically pulls colors from the colorscheme. I submitted a PR to airline itself to make it look better with spacegray, but it should be working out of the box dynamically. It's confusing because as you said, the actual airline colorscheme isn't called spacegray, it's called `base16`, and that loads the colors dynamically from a variety of colorschemes.

**Comment by jordwalke** [comment]
Please reopen if you have more questions.
